import { StyleSheet } from 'react-native';

const PURPLE = '#7C3AED';

export default StyleSheet.create({
  safe: {
    flex: 1,
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: 16,
  },
  headerSpacer: {
    flex: 1,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  balanceBadge: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.45)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    shadowColor: '#020617',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0,
    shadowRadius: 8,
    elevation: 0,
  },
  balanceBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  appTitle: {
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  appSubtitle: {
    marginTop: 4,
    fontSize: 12,
  },
  themeButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 2,
    backgroundColor: 'transparent',
    shadowColor: PURPLE,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0,
    shadowRadius: 6,
    elevation: 0,
  },
  themeButtonText: {
    fontSize: 12,
    fontWeight: '600',
  },
  toast: {
    position: 'absolute',
    top: 8,
    left: 16,
    right: 16,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
    zIndex: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  toastText: {
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 32,
  },
  section: {
    marginTop: 12,
  },
  screenTabsWrap: {
    marginTop: 2,
    marginBottom: 10,
  },
  screenTabsRow: {
    gap: 8,
    paddingHorizontal: 2,
  },
  screenTabButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    backgroundColor: 'transparent',
  },
  screenTabButtonActive: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(167, 139, 250, 0.9)',
  },
  screenTabText: {
    color: '#C7D2FE',
    fontSize: 12,
    fontWeight: '600',
  },
  screenTabTextActive: {
    color: '#FFFFFF',
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 6,
    color: '#F8FAFC',
  },
  sectionSubtitle: {
    fontSize: 13,
    marginBottom: 12,
  },
  inputCard: {
    backgroundColor: 'transparent',
    borderRadius: 20,
    padding: 18,
    marginBottom: 12,
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0,
    shadowRadius: 12,
    elevation: 0,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  habitsTransparentCard: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    shadowOpacity: 0,
    elevation: 0,
  },
  input: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    marginBottom: 10,
  },
  formLabel: {
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.6,
    marginBottom: 6,
    marginTop: 4,
  },
  formHelper: {
    fontSize: 12,
    marginBottom: 8,
  },
  balanceNotice: {
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  balanceNoticeText: {
    fontSize: 13,
    fontWeight: '600',
  },
  selectField: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  selectFieldText: {
    fontSize: 14,
    fontWeight: '600',
  },
  selectFieldIcon: {
    fontSize: 12,
  },
  primaryButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0,
    shadowRadius: 16,
    elevation: 0,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 15,
  },
  disabledButton: {
    opacity: 0.5,
  },
  emptyText: {
    marginTop: 8,
    fontSize: 13,
  },
  card: {
    borderRadius: 20,
    padding: 18,
    marginBottom: 12,
    shadowColor: '#7C3AED',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0,
    shadowRadius: 10,
    elevation: 0,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  weekBanner: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    shadowColor: PURPLE,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0,
    shadowRadius: 10,
    elevation: 0,
  },
  weekBannerText: {
    color: '#FFFFFF',
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  listTitle: {
    fontSize: 22,
    fontWeight: '800',
  },
  sectionUnderline: {
    width: 60,
    height: 4,
    borderRadius: 999,
    backgroundColor: PURPLE,
    marginTop: 6,
    marginBottom: 12,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 12,
  },
  filterButton: {
    flexGrow: 1,
    flexBasis: '30%',
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterButtonFull: {
    flexBasis: '100%',
  },
  filterButtonActive: {
    backgroundColor: 'transparent',
    borderColor: PURPLE,
    shadowColor: PURPLE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0,
    shadowRadius: 8,
    elevation: 0,
  },
  filterButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#C7D2FE',
  },
  filterButtonTextActive: {
    color: '#FFFFFF',
  },
  emptyStateCard: {
    borderRadius: 18,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    borderStyle: 'dashed',
    paddingVertical: 28,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    marginBottom: 12,
  },
  emptyStateIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  emptyStateTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
  },
  emptyStateSubtitle: {
    fontSize: 13,
    textAlign: 'center',
  },
  secondaryButton: {
    marginTop: 10,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#1E293B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0,
    shadowRadius: 8,
    elevation: 0,
  },
  secondaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 14,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  cardSubtitle: {
    fontSize: 13,
    marginTop: 4,
  },
  progressText: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: '500',
  },
  smallPurpleButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    shadowColor: '#020617',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0,
    shadowRadius: 6,
    elevation: 0,
  },
  disabledSmallButton: {
    opacity: 0.5,
  },
  smallPurpleButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  habitInlineButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0,
    shadowRadius: 10,
    elevation: 0,
  },
  habitInlineButtonText: {
    color: '#E2E8F0',
    fontSize: 12,
    fontWeight: '700',
  },
  cardRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  progressBlock: {
    marginTop: 8,
  },
  progressLabel: {
    fontSize: 11,
    marginBottom: 4,
  },
  progressBar: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#1E293B',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#22C55E',
  },
  progressFillWarning: {
    height: '100%',
    backgroundColor: '#F59E0B',
  },
  optionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
    marginBottom: 8,
  },
  optionChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    backgroundColor: 'transparent',
  },
  habitOptionChip: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  habitOptionChipActive: {
    backgroundColor: 'transparent',
    borderColor: PURPLE,
  },
  optionChipActive: {
    backgroundColor: 'transparent',
    borderColor: PURPLE,
  },
  optionChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#C7D2FE',
  },
  optionChipTextActive: {
    color: '#FFFFFF',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  statItem: {
    flex: 1,
  },
  statLabel: {
    fontSize: 11,
    marginBottom: 2,
  },
  statValue: {
    fontSize: 18,
    fontWeight: '700',
  },
  statValueSmall: {
    fontSize: 14,
    fontWeight: '600',
  },
  participantRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  challengeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
  },
  challengeStatusRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  },
  statusChip: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    backgroundColor: 'transparent',
  },
  statusChipActive: {
    backgroundColor: 'transparent',
    borderColor: PURPLE,
  },
  statusChipText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#C7D2FE',
  },
  statusChipTextActive: {
    color: '#FFFFFF',
  },
  paginationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    gap: 8,
  },
  weekDaysRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  weekDayCard: {
    width: '30%',
    minWidth: 90,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    padding: 8,
    backgroundColor: 'transparent',
  },
  weekDayLabel: {
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 6,
  },
  weekDayActions: {
    flexDirection: 'row',
    gap: 6,
  },
  weekDayButton: {
    flex: 1,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  weekDayButtonDone: {
    backgroundColor: 'transparent',
    borderColor: '#16A34A',
  },
  weekDayButtonFail: {
    backgroundColor: 'transparent',
    borderColor: '#DC2626',
  },
  weekDayButtonText: {
    fontSize: 14,
  },
  weekDayButtonTextActive: {
    fontWeight: '700',
  },
  statusBadge: {
    marginLeft: 'auto',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#E2E8F0',
  },
  participantIndex: {
    fontSize: 12,
    width: 26,
  },
  participantName: {
    fontSize: 14,
    fontWeight: '500',
  },
  winnerCard: {
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#334155',
  },
  winnerLabel: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 2,
  },
  winnerName: {
    fontSize: 14,
    fontWeight: '700',
  },
  backButton: {
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  backButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
  },
  backButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#EF4444',
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 20,
  },
  brandHeader: {
    alignItems: 'center',
    marginBottom: 18,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  brandIcon: {
    width: 34,
    height: 34,
    borderRadius: 8,
  },
  brandTitle: {
    fontSize: 30,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 1.6,
    textShadowColor: 'rgba(255, 255, 255, 0.45)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 12,
  },
  brandSubtitle: {
    marginTop: 6,
    fontSize: 13,
    color: '#94A3B8',
    textAlign: 'center',
  },
  appIcon: {
    width: 120,
    height: 120,
    borderRadius: 24,
    shadowColor: PURPLE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  homeTitle: {
    fontSize: 30,
    fontWeight: '900',
    marginBottom: 8,
    textAlign: 'center',
  },
  appNameTitle: {
    color: '#FFFFFF',
    letterSpacing: 2,
    textShadowColor: 'rgba(255, 255, 255, 0.45)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 14,
  },
  homeSubtitle: {
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 12,
    textAlign: 'center',
  },
  menuButtons: {
    marginTop: 8,
    gap: 10,
  },
  heroCard: {
    backgroundColor: 'transparent',
    borderRadius: 24,
    padding: 20,
    marginTop: 12,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0,
    shadowRadius: 20,
    elevation: 0,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  heroTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#F8FAFC',
    marginBottom: 6,
    textAlign: 'center',
  },
  heroSubtitle: {
    fontSize: 13,
    color: '#C7D2FE',
    textAlign: 'center',
    marginBottom: 16,
  },
  heroButton: {
    marginBottom: 10,
  },
  gradientButton: {
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0,
    shadowRadius: 20,
    elevation: 0,
  },
  habitTransparentButton: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(255, 255, 255, 0.35)',
    shadowOpacity: 0,
    elevation: 0,
  },
  gradientButtonAccent: {
    backgroundColor: 'transparent',
    borderColor: PURPLE,
  },
  gradientButtonText: {
    color: '#E2E8F0',
    fontWeight: '700',
    fontSize: 14,
    letterSpacing: 0.2,
  },
  gradientButtonTextAccent: {
    color: '#FFFFFF',
  },
  gradientButtonIcon: {
    marginRight: 8,
  },
  habitsCreateButton: {
    marginTop: 2,
  },
  footerNote: {
    textAlign: 'center',
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 16,
  },
  footerTiny: {
    textAlign: 'center',
    fontSize: 11,
    color: '#64748B',
    marginTop: 4,
  },
  menuButton: {
    borderRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 20,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0,
    shadowRadius: 10,
    elevation: 0,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  menuButtonHabits: {
    backgroundColor: 'transparent',
  },
  menuButtonChallenge: {
    backgroundColor: 'transparent',
  },
  menuButtonProfile: {
    backgroundColor: 'transparent',
  },
  menuButtonHelp: {
    backgroundColor: 'transparent',
  },
  menuButtonTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatarButtonsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
    marginBottom: 6,
  },
  avatarCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: PURPLE,
    shadowColor: PURPLE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0,
    shadowRadius: 8,
    elevation: 0,
  },
  avatarText: {
    fontSize: 36,
  },
  avatarImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
  },
  smallGhostButton: {
    alignSelf: 'flex-start',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    backgroundColor: 'transparent',
    marginTop: 4,
    marginBottom: 4,
  },
  smallGhostButtonText: {
    fontSize: 12,
    fontWeight: '600',
  },
  profileButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    gap: 8,
  },
  smallOutlineButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0,
    shadowRadius: 4,
    elevation: 0,
  },
  smallOutlineButtonText: {
    fontSize: 12,
    fontWeight: '600',
  },
  profileStatLine: {
    marginTop: 4,
    fontSize: 13,
  },
  statsHeroValue: {
    fontSize: 32,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 8,
  },
  statsHeroLabel: {
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 0.6,
    marginBottom: 12,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 6,
    marginBottom: 12,
    gap: 12,
  },
  statsTile: {
    width: '48%',
    backgroundColor: 'transparent',
    borderRadius: 18,
    paddingVertical: 18,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0,
    shadowRadius: 10,
    elevation: 0,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  statsTileSuccess: {
    borderTopWidth: 4,
    borderTopColor: '#10B981',
  },
  statsTileFail: {
    borderTopWidth: 4,
    borderTopColor: '#EF4444',
  },
  statsTileActive: {
    borderTopWidth: 4,
    borderTopColor: PURPLE,
  },
  statsTileTotal: {
    borderTopWidth: 4,
    borderTopColor: PURPLE,
  },
  statsTileValue: {
    fontSize: 26,
    fontWeight: '800',
    marginBottom: 6,
  },
  statsTileLabel: {
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  statsDetailTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginTop: 8,
  },
  authErrorText: {
    fontSize: 12,
    marginBottom: 4,
  },
  authHintText: {
    fontSize: 11,
    marginTop: 8,
  },
  authToggleRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  authToggleButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authToggleActive: {
    backgroundColor: 'transparent',
    borderColor: PURPLE,
  },
  authToggleText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#C7D2FE',
  },
  authToggleTextActive: {
    color: '#FFFFFF',
  },
  balanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 8,
  },
  balanceValue: {
    fontSize: 18,
    fontWeight: '800',
  },
  balanceBar: {
    backgroundColor: 'transparent',
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    marginBottom: 10,
  },
  balanceBarText: {
    color: '#E2E8F0',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  topUpButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 6,
  },
  topUpButton: {
    flex: 1,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    borderRadius: 999,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0,
    shadowRadius: 6,
    elevation: 0,
  },
  topUpButtonText: {
    color: '#E2E8F0',
    fontWeight: '800',
    fontSize: 13,
  },
  logoutButton: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.7)',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0,
    shadowRadius: 8,
    elevation: 0,
  },
  logoutButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 16,
  },
});
